name: Q3

on:
  workflow_dispatch:

jobs:
  archive-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Q3_archive_java.txt
        run: |
          echo "Antoine Paunet" > Q3_archive_java.txt
          echo "" >> Q3_archive_java.txt
          cat Q3.java >> Q3_archive_java.txt

      - name: Commit et Push du .txt
        run: |
          git config --global user.name PAUNETantoine
          git config user.email paunet.antoine@gmail.com

          git pull
          git add Q3_archive_java.txt
          git commit -m "Ajout automatique de l’archive java"
          git push

